Hi Darius,
Thanks for the update!  I "think"  that there might have been a change upstream to the validation url used in the test package.  I pulled down directly from the repo and the test results were the same. This update is to change the assertion to match what is returned in both this PR and the go get version I pulled and tested:

(nscli) [07/19/18 20:38 crewjam]#
(nscli) [07/19/18 20:38 crewjam]# go get -u github.com/crewjam/saml/samlsp
(nscli) [07/19/18 20:38 crewjam]# cd saml/
(nscli) [07/19/18 20:38 saml]# go test
2018/07/19 20:38:46 failed to parse request: cannot decompress request: flate: corrupt input before offset 8
2018/07/19 20:38:46 cannot find service provider: https://wrong.url/metadata

----------------------------------------------------------------------
FAIL: identity_provider_test.go:713: IdentityProviderTest.TestMakeResponse

identity_provider_test.go:753:
    c.Assert(responseStr, DeepEquals, ""+
        "<samlp:Response xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" ID=\"id-282a2c2e30323436383a3c3e40424446484a4c4e\" InResponseTo=\"id-00020406080a0c0e10121416181a1c1e\" Version=\"2.0\" IssueInstant=\"2015-12-01T01:57:09Z\" Destination=\"https://sp.example.com/saml2/acs\">\n"+
        "  <saml:Issuer Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://idp.example.com/saml/metadata</saml:Issuer>\n"+
        "  <ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">\n"+
        "    <ds:SignedInfo>\n"+
        "      <ds:CanonicalizationMethod Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/>\n"+
        "      <ds:SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/>\n"+
        "      <ds:Reference URI=\"#id-282a2c2e30323436383a3c3e40424446484a4c4e\">\n"+
        "        <ds:Transforms>\n"+
        "          <ds:Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/>\n"+
        "          <ds:Transform Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/>\n"+
        "        </ds:Transforms>\n"+
        "        <ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>\n"+
        "        <ds:DigestValue>fGqTakd3fq3s1utz7xTvzJtQc+E=</ds:DigestValue>\n"+
        "      </ds:Reference>\n"+
        "    </ds:SignedInfo>\n"+
        "    <ds:SignatureValue>yXty6VQCvvF6QAR+vXZtLq2/r8Jt2B9jExD1vVfvWY+S1sKPZbNbaKl69YHYXU8lkhymlVNaMsaezQWDisbNfPe0R0UWysp2rfIXpVDGTdp/YHPj1MIODMPrlgWFfcJjgGxox0tTVzaFyOJFSPhn4G8wEI86WHuePnjRcenfxyk=</ds:SignatureValue>\n"+
        "    <ds:KeyInfo>\n"+
        "      <ds:X509Data>\n"+
        "        <ds:X509Certificate>MIIB7zCCAVgCCQDFzbKIp7b3MTANBgkqhkiG9w0BAQUFADA8MQswCQYDVQQGEwJVUzELMAkGA1UECAwCR0ExDDAKBgNVBAoMA2ZvbzESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTEzMTAwMjAwMDg1MVoXDTE0MTAwMjAwMDg1MVowPDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkdBMQwwCgYDVQQKDANmb28xEjAQBgNVBAMMCWxvY2FsaG9zdDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA1PMHYmhZj308kWLhZVT4vOulqx/9ibm5B86fPWwUKKQ2i12MYtz07tzukPymisTDhQaqyJ8Kqb/6JjhmeMnEOdTvSPmHO8m1ZVveJU6NoKRn/mP/BD7FW52WhbrUXLSeHVSKfWkNk6S4hk9MV9TswTvyRIKvRsw0X/gfnqkroJcCAwEAATANBgkqhkiG9w0BAQUFAAOBgQCMMlIO+GNcGekevKgkakpMdAqJfs24maGb90DvTLbRZRD7Xvn1MnVBBS9hzlXiFLYOInXACMW5gcoRFfeTQLSouMM8o57h0uKjfTmuoWHLQLi6hnF+cvCsEFiJZ4AbF+DgmO6TarJ8O05t8zvnOwJlNCASPZRH/JmF8tX0hoHuAQ==</ds:X509Certificate>\n"+
        "      </ds:X509Data>\n"+
        "    </ds:KeyInfo>\n"+
        "  </ds:Signature>\n"+
        "  <samlp:Status>\n"+
        "    <samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Success\"/>\n"+
        "  </samlp:Status>\n"+
        "  <this-is-an-encrypted-assertion xmlns=\"http://www.w3.org/XML/1998/namespace\"/>\n"+
        "</samlp:Response>\n")
... obtained string = "" +
...     "<samlp:Response xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" ID=\"id-282a2c2e30323436383a3c3e40424446484a4c4e\" InResponseTo=\"id-00020406080a0c0e10121416181a1c1e\" Version=\"2.0\" IssueInstant=\"2015-12-01T01:57:09Z\" Destination=\"https://sp.example.com/saml2/acs\">\n" +
...     "  <saml:Issuer Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://idp.example.com/saml/metadata</saml:Issuer>\n" +
...     "  <ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">\n" +
...     "    <ds:SignedInfo>\n" +
...     "      <ds:CanonicalizationMethod Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/>\n" +
...     "      <ds:SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/>\n" +
...     "      <ds:Reference URI=\"#id-282a2c2e30323436383a3c3e40424446484a4c4e\">\n" +
...     "        <ds:Transforms>\n" +
...     "          <ds:Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/>\n" +
...     "          <ds:Transform Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/>\n" +
...     "        </ds:Transforms>\n" +
...     "        <ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>\n" +
...     "        <ds:DigestValue>KsbyS2V2/QCarAksPQyV5s3PVDk=</ds:DigestValue>\n" +
...     "      </ds:Reference>\n" +
...     "    </ds:SignedInfo>\n" +
...     "    <ds:SignatureValue>paj/Jq/TTvYXu35Jtyevmu8bn2DZecfaj/wu8l7mY2sN++w9QL/sLZoyyJk6WsAsS0NMMOt8o5WN7EU+bVlbQ6VQbf2VO9gEPbONMdpQ8gfrvMiLo5vRS22iRaPehIH8gvWxAq64vWWt94OihpndNRt782K/0h/NvXBj+4vK7V8=</ds:SignatureValue>\n" +
...     "    <ds:KeyInfo>\n" +
...     "      <ds:X509Data>\n" +
...     "        <ds:X509Certificate>MIIB7zCCAVgCCQDFzbKIp7b3MTANBgkqhkiG9w0BAQUFADA8MQswCQYDVQQGEwJVUzELMAkGA1UECAwCR0ExDDAKBgNVBAoMA2ZvbzESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTEzMTAwMjAwMDg1MVoXDTE0MTAwMjAwMDg1MVowPDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkdBMQwwCgYDVQQKDANmb28xEjAQBgNVBAMMCWxvY2FsaG9zdDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA1PMHYmhZj308kWLhZVT4vOulqx/9ibm5B86fPWwUKKQ2i12MYtz07tzukPymisTDhQaqyJ8Kqb/6JjhmeMnEOdTvSPmHO8m1ZVveJU6NoKRn/mP/BD7FW52WhbrUXLSeHVSKfWkNk6S4hk9MV9TswTvyRIKvRsw0X/gfnqkroJcCAwEAATANBgkqhkiG9w0BAQUFAAOBgQCMMlIO+GNcGekevKgkakpMdAqJfs24maGb90DvTLbRZRD7Xvn1MnVBBS9hzlXiFLYOInXACMW5gcoRFfeTQLSouMM8o57h0uKjfTmuoWHLQLi6hnF+cvCsEFiJZ4AbF+DgmO6TarJ8O05t8zvnOwJlNCASPZRH/JmF8tX0hoHuAQ==</ds:X509Certificate>\n" +
...     "      </ds:X509Data>\n" +
...     "    </ds:KeyInfo>\n" +
...     "  </ds:Signature>\n" +
...     "  <samlp:Status>\n" +
...     "    <samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Success\"/>\n" +
...     "  </samlp:Status>\n" +
...     "  <this-is-an-encrypted-assertion/>\n" +
...     "</samlp:Response>\n"
... expected string = "" +
...     "<samlp:Response xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" ID=\"id-282a2c2e30323436383a3c3e40424446484a4c4e\" InResponseTo=\"id-00020406080a0c0e10121416181a1c1e\" Version=\"2.0\" IssueInstant=\"2015-12-01T01:57:09Z\" Destination=\"https://sp.example.com/saml2/acs\">\n" +
...     "  <saml:Issuer Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://idp.example.com/saml/metadata</saml:Issuer>\n" +
...     "  <ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\">\n" +
...     "    <ds:SignedInfo>\n" +
...     "      <ds:CanonicalizationMethod Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/>\n" +
...     "      <ds:SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/>\n" +
...     "      <ds:Reference URI=\"#id-282a2c2e30323436383a3c3e40424446484a4c4e\">\n" +
...     "        <ds:Transforms>\n" +
...     "          <ds:Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/>\n" +
...     "          <ds:Transform Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/>\n" +
...     "        </ds:Transforms>\n" +
...     "        <ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>\n" +
...     "        <ds:DigestValue>fGqTakd3fq3s1utz7xTvzJtQc+E=</ds:DigestValue>\n" +
...     "      </ds:Reference>\n" +
...     "    </ds:SignedInfo>\n" +
...     "    <ds:SignatureValue>yXty6VQCvvF6QAR+vXZtLq2/r8Jt2B9jExD1vVfvWY+S1sKPZbNbaKl69YHYXU8lkhymlVNaMsaezQWDisbNfPe0R0UWysp2rfIXpVDGTdp/YHPj1MIODMPrlgWFfcJjgGxox0tTVzaFyOJFSPhn4G8wEI86WHuePnjRcenfxyk=</ds:SignatureValue>\n" +
...     "    <ds:KeyInfo>\n" +
...     "      <ds:X509Data>\n" +
...     "        <ds:X509Certificate>MIIB7zCCAVgCCQDFzbKIp7b3MTANBgkqhkiG9w0BAQUFADA8MQswCQYDVQQGEwJVUzELMAkGA1UECAwCR0ExDDAKBgNVBAoMA2ZvbzESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTEzMTAwMjAwMDg1MVoXDTE0MTAwMjAwMDg1MVowPDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkdBMQwwCgYDVQQKDANmb28xEjAQBgNVBAMMCWxvY2FsaG9zdDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA1PMHYmhZj308kWLhZVT4vOulqx/9ibm5B86fPWwUKKQ2i12MYtz07tzukPymisTDhQaqyJ8Kqb/6JjhmeMnEOdTvSPmHO8m1ZVveJU6NoKRn/mP/BD7FW52WhbrUXLSeHVSKfWkNk6S4hk9MV9TswTvyRIKvRsw0X/gfnqkroJcCAwEAATANBgkqhkiG9w0BAQUFAAOBgQCMMlIO+GNcGekevKgkakpMdAqJfs24maGb90DvTLbRZRD7Xvn1MnVBBS9hzlXiFLYOInXACMW5gcoRFfeTQLSouMM8o57h0uKjfTmuoWHLQLi6hnF+cvCsEFiJZ4AbF+DgmO6TarJ8O05t8zvnOwJlNCASPZRH/JmF8tX0hoHuAQ==</ds:X509Certificate>\n" +
...     "      </ds:X509Data>\n" +
...     "    </ds:KeyInfo>\n" +
...     "  </ds:Signature>\n" +
...     "  <samlp:Status>\n" +
...     "    <samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Success\"/>\n" +
...     "  </samlp:Status>\n" +
...     "  <this-is-an-encrypted-assertion xmlns=\"http://www.w3.org/XML/1998/namespace\"/>\n" +
...     "</samlp:Response>\n"
... String difference:
...     [12]: "        <ds:DigestValue>KsbyS2V2/QCarAksPQyV5s3PVDk=</ds:DigestValue>" != "        <ds:DigestValue>fGqTakd3fq3s1utz7xTvzJtQc+E=</ds:DigestValue>"
...     [15]: "    <ds:SignatureValue>paj/Jq/TTvYXu35Jtyevmu8bn2DZecfaj/wu8l7mY2sN++w9QL/sLZoyyJk6WsAsS0NMMOt8o5WN7EU+bVlbQ6VQbf2VO9gEPbONMdpQ8gfrvMiLo5vRS22iRaPehIH8gvWxAq64vWWt94OihpndNRt782K/0h/NvXBj+4vK7V8=</ds:SignatureValue>" != "    <ds:SignatureValue>yXty6VQCvvF6QAR+vXZtLq2/r8Jt2B9jExD1vVfvWY+S1sKPZbNbaKl69YHYXU8lkhymlVNaMsaezQWDisbNfPe0R0UWysp2rfIXpVDGTdp/YHPj1MIODMPrlgWFfcJjgGxox0tTVzaFyOJFSPhn4G8wEI86WHuePnjRcenfxyk=</ds:SignatureValue>"
...     [25]: "  <this-is-an-encrypted-assertion/>" != "  <this-is-an-encrypted-assertion xmlns=\"http://www.w3.org/XML/1998/namespace\"/>"

2018/07/19 20:38:46 failed to parse request: cannot decode request: illegal base64 data at input byte 0
2018/07/19 20:38:46 failed to parse request: illegal base64 data at input byte 0
saml.EntityDescriptor{
    XMLName:    xml.Name{},
    EntityID:   "https://dev.aa.kndr.org/users/auth/saml/metadata",
    ID:         "_af805d1c-c2e3-444e-9cf5-efc664eeace6",
    ValidUntil: time.Time{
        wall: 0x2f072f40,
        ext:  63116769906,
        loc:  (*time.Location)(nil),
    },
    CacheDuration:     3600000000000,
    Signature:         (*etree.Element)(nil),
    RoleDescriptors:   nil,
    IDPSSODescriptors: nil,
    SPSSODescriptors:  {
        {
            XMLName:       xml.Name{Space:"urn:oasis:names:tc:SAML:2.0:metadata", Local:"SPSSODescriptor"},
            SSODescriptor: saml.SSODescriptor{
                RoleDescriptor: saml.RoleDescriptor{
                    ID:                         "",
                    ValidUntil:                 time.Time{},
                    CacheDuration:              0,
                    ProtocolSupportEnumeration: "urn:oasis:names:tc:SAML:2.0:protocol",
                    ErrorURL:                   "",
                    Signature:                  (*etree.Element)(nil),
                    KeyDescriptors:             nil,
                    Organization:               (*saml.Organization)(nil),
                    ContactPeople:              nil,
                },
                ArtifactResolutionServices: nil,
                SingleLogoutServices:       nil,
                ManageNameIDServices:       nil,
                NameIDFormats:              nil,
            },
            AuthnRequestsSigned:       &bool(false),
            WantAssertionsSigned:      &bool(false),
            AssertionConsumerServices: {
                {
                    Binding:          "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
                    Location:         "https://dev.aa.kndr.org/users/auth/saml/callback",
                    ResponseLocation: (*string)(nil),
                    Index:            0,
                    IsDefault:        &bool(true),
                },
            },
            AttributeConsumingServices: {
                {
                    Index:        1,
                    IsDefault:    &bool(true),
                    ServiceNames: {
                        {Lang:"", Value:"Required attributes"},
                    },
                    ServiceDescriptions: nil,
                    RequestedAttributes: {
                        {
                            Attribute: saml.Attribute{
                                FriendlyName: "Email address",
                                Name:         "email",
                                NameFormat:   "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
                                Values:       nil,
                            },
                            IsRequired: (*bool)(nil),
                        },
                        {
                            Attribute: saml.Attribute{
                                FriendlyName: "Full name",
                                Name:         "name",
                                NameFormat:   "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
                                Values:       nil,
                            },
                            IsRequired: (*bool)(nil),
                        },
                        {
                            Attribute: saml.Attribute{
                                FriendlyName: "Given name",
                                Name:         "first_name",
                                NameFormat:   "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
                                Values:       nil,
                            },
                            IsRequired: (*bool)(nil),
                        },
                        {
                            Attribute: saml.Attribute{
                                FriendlyName: "Family name",
                                Name:         "last_name",
                                NameFormat:   "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
                                Values:       nil,
                            },
                            IsRequired: (*bool)(nil),
                        },
                    },
                },
            },
        },
    },
    AuthnAuthorityDescriptors:     nil,
    AttributeAuthorityDescriptors: nil,
    PDPDescriptors:                nil,
    AffiliationDescriptor:         (*saml.AffiliationDescriptor)(nil),
    Organization:                  (*saml.Organization)(nil),
    ContactPerson:                 (*saml.ContactPerson)(nil),
    AdditionalMetadataLocations:   nil,
}[]saml.SubjectConfirmation{
    {
        Method:                  "urn:oasis:names:tc:SAML:2.0:cm:bearer",
        NameID:                  (*saml.NameID)(nil),
        SubjectConfirmationData: &saml.SubjectConfirmationData{
            NotBefore:    time.Time{},
            NotOnOrAfter: time.Time{
                wall: 0x165a0bc0,
                ext:  63584532081,
                loc:  (*time.Location)(nil),
            },
            Recipient:    "https://15661444.ngrok.io/saml2/acs",
            InResponseTo: "id-9e61753d64e928af5a7a341a97f420c9",
            Address:      "75.144.86.91",
        },
    },
}OOPS: 37 passed, 1 FAILED
--- FAIL: Test (0.06s)
FAIL
exit status 1
FAIL	github.com/crewjam/saml	0.079s