update etreeutils.TransformExcC14n signature (#478)
* update etreeutils.TransformExcC14n signature

The invocation does not match the current function signature:

```
github.com/crewjam/saml@v0.4.10/schema.go:767:41: not enough arguments in call to etreeutils.TransformExcC14n
     |  have (*etree.Element, string)
     |  want (*etree.Element, string, bool)
```

* Update go.mod

* upgrade to github.com/russellhaering/goxmldsig v1.2.0

* update go.sum

* update github.com/russellhaering/goxmldsig

* upgrade to github.com/russellhaering/goxmldsig v1.2.0